[env]
LUA_PATH = "{{config_root}}/nvim/lua/?.lua;;"

[tasks]
format = [
    "stylua .",
    "treefmt",
    "shfmt -w .",
    "taplo format .",
]
test = [
    "busted .",
]
lint = [
    "lua-language-server --check=nvim",
]
